#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""빈도 401-600번째 단어에 한글 의미 추가 (배치 9-10)"""

import json
import sys

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# 401-600번째 단어의 한글 의미
meanings_batch9_10 = {
    # 401-500
    "asked": "질문한",
    "task": "작업",
    "exercise": "연습, 실행",
    "owners": "소유자들",
    "start": "시작하다",
    "attempt": "시도",
    "lightweight": "경량의",
    "identifies": "식별한다",
    "sent": "전송된",
    "cybersecurity": "사이버 보안",
    "detailed": "상세한",
    "documented": "문서화된",
    "limits": "제한들",
    "suited": "적합한",
    "hired": "고용된",
    "expected": "예상된",
    "standardization": "표준화",
    "stateful": "상태 유지",
    "defining": "정의하는",
    "browser": "브라우저",
    "unnecessary": "불필요한",
    "conditions": "조건들",
    "segmentation": "분할",
    "documents": "문서들",
    "examine": "검토하다",
    "compliant": "준수하는",
    "administrators": "관리자들",
    "isolate": "격리하다",
    "air": "공기, 무선",
    "notify": "알리다",
    "online": "온라인",
    "members": "멤버들",
    "settings": "설정들",
    "official": "공식적인",
    "attempts": "시도들",
    "good": "좋은",
    "exploits": "악용하다, 익스플로잇",
    "interest": "이익, 관심",
    "hours": "시간들",
    "connectivity": "연결성",
    "changed": "변경된",
    "direct": "직접적인",
    "negative": "부정적인",
    "destination": "목적지",
    "applying": "적용하는",
    "better": "더 나은",
    "networking": "네트워킹",
    "left": "왼쪽, 남은",
    "match": "일치하다",
    "laws": "법률들",
    "top": "상단",
    "recent": "최근의",
    "board": "보드, 이사회",
    "embedded": "내장된",
    "length": "길이",
    "tasks": "작업들",
    "rivest": "Rivest (암호학자)",
    "stolen": "도난당한",
    "executable": "실행 가능한",
    "secondary": "2차의",
    "custodian": "관리인",
    "mitigating": "완화하는",
    "isolated": "격리된",
    "certified": "인증된",
    "return": "반환하다",
    "scenario": "시나리오",
    "therefore": "따라서",
    "effectively": "효과적으로",
    "central": "중앙의",
    "office": "사무실",
    "self": "자기 자신",
    "issued": "발급된",
    "prevents": "방지한다",
    "complex": "복잡한",
    "removing": "제거하는",
    "insurance": "보험",
    "endpoints": "엔드포인트들",
    "locations": "위치들",
    "circuit": "회로",
    "bit": "비트",
    "machines": "기계들",
    "dial": "다이얼",
    "crucial": "중요한",
    "pll": "PLL (위상 고정 루프)",
    "damage": "손상",
    "forgery": "위조",
    "csrf": "CSRF (사이트 간 요청 위조)",
    "configurations": "구성들",
    "investigate": "조사하다",
    "accurate": "정확한",
    "institute": "기관",
    "immediately": "즉시",
    "efforts": "노력들",
    "scenarios": "시나리오들",
    "switch": "스위치",
    "capture": "캡처하다",
    "recently": "최근에",
    "inform": "알리다",
    "transit": "전송",
    "exposures": "노출들",
    
    # 501-600
    "volatility": "휘발성",
    "shelf": "선반",
    "patching": "패칭",
    "track": "추적하다",
    "want": "원하다",
    "suppression": "억제",
    "profession": "전문직",
    "cissp": "CISSP (공인 정보 시스템 보안 전문가)",
    "enforcement": "강제",
    "room": "방",
    "environmental": "환경의",
    "drop": "드롭하다",
    "competent": "유능한",
    "hypertext": "하이퍼텍스트",
    "profile": "프로필",
    "evaluated": "평가된",
    "scans": "스캔들",
    "ongoing": "진행 중인",
    "sites": "사이트들",
    "sod": "SOD (직무 분리)",
    "concerned": "관련된",
    "modification": "수정",
    "choose": "선택하다",
    "messages": "메시지들",
    "backups": "백업들",
    "occurred": "발생한",
    "cyber": "사이버",
    "prepare": "준비하다",
    "added": "추가된",
    "final": "최종의",
    "rp": "RP (신뢰 당사자)",
    "sending": "전송하는",
    "created": "생성된",
    "proxies": "프록시들",
    "concept": "개념",
    "selection": "선택",
    "mechanisms": "메커니즘들",
    "removal": "제거",
    "fault": "결함",
    "isolation": "격리",
    "enter": "입력하다",
    "enumeration": "열거",
    "creation": "생성",
    "idaas": "IDaaS (신원 서비스)",
    "specifically": "구체적으로",
    "violations": "위반들",
    "accessing": "접근하는",
    "guidelines": "가이드라인들",
    "sender": "발신자",
    "cc": "CC (카본 카피)",
    "utilizing": "활용하는",
    "rule": "규칙",
    "works": "작동한다",
    "validated": "검증된",
    "met": "만족한",
    "successful": "성공적인",
    "easier": "더 쉬운",
    "states": "상태들",
    "resolution": "해결",
    "encrypts": "암호화한다",
    "restoring": "복원하는",
    "signal": "신호",
    "transmitted": "전송된",
    "installing": "설치하는",
    "put": "놓다",
    "untrusted": "신뢰할 수 없는",
    "sufficient": "충분한",
    "old": "오래된",
    "phases": "단계들",
    "context": "컨텍스트",
    "agent": "에이전트",
    "id": "ID (식별자)",
    "plaintext": "평문",
    "efficient": "효율적인",
    "instead": "대신에",
    "ecc": "ECC (타원 곡선 암호)",
    "contents": "내용들",
    "typed": "입력된",
    "outage": "중단",
    "something": "무언가",
    "valuable": "가치 있는",
    "restore": "복원하다",
    "highest": "가장 높은",
    "mutual": "상호의",
    "integrate": "통합하다",
    "retain": "유지하다",
    "facilitate": "촉진하다",
    "schedule": "일정",
    "processor": "프로세서",
    "setting": "설정",
    "operates": "운영한다",
    "experience": "경험",
    "websites": "웹사이트들",
    "phone": "전화",
    "distribution": "분배",
    "weak": "약한",
    "relying": "의존하는",
    "side": "측면",
    "chap": "CHAP (챌린지 핸드셰이크 인증 프로토콜)",
    "presentation": "프레젠테이션"
}

def add_meanings():
    """의미 추가"""
    with open('data/cissp_problem_vocabulary.json', 'r', encoding='utf-8') as f:
        vocab = json.load(f)
    
    added_count = 0
    for word, meaning in meanings_batch9_10.items():
        if word in vocab:
            if not vocab[word].get('meaning') or vocab[word].get('meaning', '').strip() == '':
                vocab[word]['meaning'] = meaning
                added_count += 1
                if added_count <= 30:
                    print(f"[OK] {word}: {meaning}")
    
    with open('data/cissp_problem_vocabulary.json', 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)
    
    print(f"\n총 {added_count}개 단어에 의미가 추가되었습니다.")
    
    # 남은 단어 수 확인
    remaining = [(w, data) for w, data in vocab.items() 
                if not data.get('meaning') or data.get('meaning', '').strip() == '']
    print(f"남은 의미 없는 단어: {len(remaining)}개")

if __name__ == '__main__':
    add_meanings()

